name: navolaya_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+4
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Dio is http client library for API's
  dio: ^4.0.6
  # Flutter blocs is state management library
  flutter_bloc: ^8.0.1
  # Functional programming thingies
  dartz: ^0.10.1
  # Manage session library
  shared_preferences: ^2.0.7
  # File picker library to access storage and add attachments
  file_picker: ^5.0.1
  # Encode and decode json files
  json_annotation: ^4.0.1
  # Serialize and Deserialize json files
  json_serializable: 4.1.4
  # Service locator (Dependency Injection)
  get_it: ^7.2.0
  # To check network connectivity
  connectivity: ^3.0.6
  # To get locale for date time and language
  intl: ^0.17.0
  # To log all the Log level (debug,verbose,info,error,wtf[what the terrible failure log])
  logger: ^1.1.0
  # To get all font and icons for customizations
  font_awesome_flutter: ^10.1.0
  # Launch any type of url in the package and render all type of files
  url_launcher: ^6.1.5
  # re call the method or API by pulling down the view to refresh the UI
  #pull_to_refresh: ^2.0.0
  # To check Value Equality between objects same Type or data we use Equatable
  equatable: ^2.0.3
  # To Select Country code for mobile number verification
  # country_code_picker: ^2.0.2
  country_picker: ^2.0.15
  # expandable widget package for expanding a view in settings page
  expandable: ^5.0.1
  # Image picker dependency to upload image from either camera or gallery
  image_picker: ^0.8.5+3
  # Image cropper for setting aspect ratio and cropping image to set into the view properly
  image_cropper: ^2.0.3
  # Image Manipulation library for resizing and manage ratio
  image: ^3.2.0
  # To write image to specific directory in flutter
  path_provider: ^2.0.11
  # Image loading functionality with loading load and error callbacks and handling methods built in
  cached_network_image: ^3.2.1
  # To show error , info or success messages with custom view and position another Flush bar is used.
  another_flushbar: ^1.10.29
  # To retrieve users who are near by the location provided.
  location: ^4.4.0
  # To Load html text in About us , Privacy Policy and Terms and Condition.
  #flutter_html: ^2.2.1
  flutter_html: ^3.0.0-alpha.5
  # Accordion view to show FAQ's.
  accordion: ^2.1.1
  # Notifies when keyboard is opened and closed
  flutter_keyboard_visibility: ^5.3.0
  # AutoComplete text field for replacing dropdown in this
  flutter_typeahead: ^4.0.0
  # AutoComplete entered address by user
  flutter_google_places: ^0.3.0
  # to fetch locality of the user from selected latitude and longitude
  geocoding: ^2.0.4
  # Chat bubble bg
  flutter_chat_bubble: ^2.0.0
  # Socket connection with web for chats and to read live message from server to app and vice versa
  socket_io_client: ^1.0.1
  # Execution of API's in background are asynchronous to make it synchronous we will use queue
  queue: ^3.1.0+1
  # 3D rendering effects for all the widgets
  flutter_neumorphic: ^3.2.0
  # Add Validation in phone number
  phone_number: ^1.0.0
  # Grouping list for search
  grouped_list: ^5.1.2
  # For Dotted bg or box decoration
  dotted_border: ^2.0.0+2
  # Showing Image Url , with handling loading ,error handling and waiting for whole image to render
  image_network: ^2.5.1
  # For firebase notification
  firebase_messaging: ^13.0.0
  # For firebase core packages
  firebase_core: ^1.21.1
  # For firebase local notifications
  flutter_local_notifications: ^9.8.0+1
  # For clearing local notifications and badge counts
  eraser: ^2.0.1
  # PDF viewer
  syncfusion_flutter_pdfviewer: ^20.2.40-beta
  # Google Place API to search address
  google_place: ^0.4.7
  # AutoText size implementation
  auto_size_text: ^3.0.0
  # Create JWT token , decode , verify
  dart_jsonwebtoken: ^2.4.2
  # Flutter Share app with text and links
  flutter_share: ^2.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat_Medium.ttf

    - family: Poppins
      fonts:
        - asset: fonts/Poppins_Regular.ttf
